I'm sorry, but an uncaught exception occurred.

While running game code:
  File "/home/tom/ab/renpy/renpygame-demo/game/script.rpy", line 31, in script
  File "/home/tom/ab/renpy/renpygame-demo/game/script.rpy", line 31, in <module>
AttributeError: 'Score' object has no attribute 'font'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/tom/ab/renpy/renpygame-demo/game/script.rpy", line 31, in script
  File "C:\Users\Laura Luo\Desktop\renpy\renpy-6.99.12.4-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Laura Luo\Desktop\renpy\renpy-6.99.12.4-sdk\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "/home/tom/ab/renpy/renpygame-demo/game/script.rpy", line 31, in <module>
  File "aliens.py", line 262, in main
  File "aliens.py", line 173, in __init__
  File "aliens.py", line 180, in update
AttributeError: 'Score' object has no attribute 'font'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
 
